### ISSUE TITLE
Missing dependency bigdecimal

### ISSUE THREAD

**Issue by joekohlsdorf** [Shopify/kubernetes-deploy#407]
# Bug report

When installing kubernetes-deploy on alpine:3.8 I also have to manually install `bigdecimal` to be able to run it.

**Expected behavior:**

I expect that all necessary dependencies to run kubernetes-deploy are installed when installing kubernetes-deploy.

**Actual behavior:**

```
/ # kubernetes-deploy
Traceback (most recent call last):
	19: from /usr/bin/kubernetes-deploy:23:in `<main>'
	18: from /usr/bin/kubernetes-deploy:23:in `load'
	17: from /usr/lib/ruby/gems/2.5.0/gems/kubernetes-deploy-0.23.0/exe/kubernetes-deploy:4:in `<top (required)>'
	16: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	15: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	14: from /usr/lib/ruby/gems/2.5.0/gems/kubernetes-deploy-0.23.0/lib/kubernetes-deploy.rb:5:in `<top (required)>'
	13: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	12: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	11: from /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/numeric/time.rb:3:in `<top (required)>'
	10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/duration.rb:3:in `<top (required)>'
	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/xml_mini.rb:5:in `<top (required)>'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bigdecimal (LoadError)
```

**Version(s) affected:**

0.23.0

### Steps to Reproduce

Basic Dockerfile to reproduce the issue:
```
FROM alpine:3.8
RUN apk -v --no-cache add ruby ruby-dev build-base && \
    gem install --no-rdoc --no-ri kubernetes-deploy:0.23.0
```

Then just run `kubernetes-deploy` in the created container image.

**Comment by dturn** [comment]
Hi @joekohlsdorf thanks for opening this bug report. This is interesting since `bigdecimal` is an indirect dependency via  `ActiveSupport`. If you'd like to PR the fix we'll accept it, but it might be worth trying to fix it upstream (https://github.com/rails/rails/issues/5355 looks like an old, but relevant issue).

**Comment by dturn** [comment]
BigDecimal is still part of the ruby std library. Apline appears to strip it from the `ruby` package, but not the `ruby-full` package. To fix this you can install in via your docker file or patch upstream.

**Comment by Nakilon** [comment]
Also consider `apk add ruby-bigdecimal`.
